# Generated by Django 3.2.9 on 2021-11-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='name')),
                ('last_name', models.CharField(max_length=255, verbose_name='surname')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
    ]
